FROM tamacat/tamacat-httpd:2.0-jetty-latest

COPY ./conf /usr/local/tamacat-httpd/conf
COPY ./lib /usr/local/tamacat-httpd/lib
COPY ./htdocs /usr/local/tamacat-httpd/htdocs
COPY ./webapps /usr/local/tamacat-httpd/webapps
