FROM maven:3.8.5-eclipse-temurin-17-alpine as BUILD

RUN apk update && apk upgrade && apk add --no-cache \
    bash \
    curl \
    git
    
WORKDIR /build
RUN git clone https://github.com/tamacat-cloud/tamacat-core-2.0.git
WORKDIR /build/tamacat-core-2.0
RUN --mount=type=cache,target=/root/.m2 mvn clean install

WORKDIR /build
RUN git clone https://github.com/tamacat-cloud/tamacat-httpd-2.0.git
WORKDIR /build/tamacat-httpd-2.0
RUN --mount=type=cache,target=/root/.m2 mvn clean package


###################################################3
FROM eclipse-temurin:17-jre-alpine

#LABEL maintainer="tamacat.org"

RUN apk update && apk upgrade && apk add --no-cache \
    bash \
    curl

RUN mkdir -p /usr/local/tamacat-httpd/lib
WORKDIR /usr/local/tamacat-httpd

COPY --from=BUILD /build/tamacat-httpd-2.0/target/tamacat-httpd-2.0-SNAPSHOT-jar-with-dependencies.jar /usr/local/tamacat-httpd/lib/tamacat-httpd-2.0-SNAPSHOT-jar-with-dependencies.jar

COPY ./conf /usr/local/tamacat-httpd/conf
COPY ./htdocs /usr/local/tamacat-httpd/htdocs
COPY ./webapps /usr/local/tamacat-httpd/webapps

ENV CLASSPATH=/usr/local/tamacat-httpd/conf:/usr/local/tamacat-httpd/lib/tamacat-httpd-2.0-SNAPSHOT-jar-with-dependencies.jar

ENV SERVICE_JSON="service.json"
ENV BIND_PORT=80

EXPOSE ${BIND_PORT}

CMD java cloud.tamacat.httpd.Httpd ${SERVICE_JSON}
